### ISSUE TITLE
Contact Page Features: Implement Contact Form

### ISSUE THREAD

**Issue by Marwa-502** [Marwa-502/Games-Website#8]
Description: Design and implement a contact form with a drop-down menu for users to select the purpose of their contact (new game request or bug report).

**Sub-tasks:**
- [x]  Create the drop-down menu
- [x]  Collect user information (name and email)
- [x]  Implement text entry for the user's message
- [x]  Validate the name and email fields using JavaScript

**Comment by Marwa-502** [comment]
completed
